# Generated by Django 4.0.4 on 2022-04-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("explorer", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollectionModel",
            new_name="Collection",
        ),
    ]
