version: "3"

services:
  postgres:
    image: postgres:12.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432

  app:
    build:
      context: ./
    container_name: starwars_explorer
    volumes:
      - ./:/opt/starwars_explorer/
    env_file:
      - .env
    expose:
      - 8000
    ports:
      - 8000:8000
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - postgres

volumes:
  postgresql_data:
